#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"; repo="$(cd "$root/../.." && pwd)"; compose=(docker compose --project-name enterprise-mcp-kit-demo --env-file "$root/.env" -f "$root/compose.yaml")
issuer='http://127.0.0.1:8081/realms/enterprise-mcp-kit'; port=8788; database='enterprise_mcp_governed_provisioning_v2'; run_id="$(date -u +%s%N)"; workdir="$(mktemp -d)"; gateway_pid=''
cleanup(){ status=$?; if [[ "$status" != 0 && -f "$workdir/gateway.log" ]]; then sed -E 's/(Bearer )[A-Za-z0-9._-]+/\1<redacted>/g' "$workdir/gateway.log" >&2; fi; [[ -z "$gateway_pid" ]] || { kill "$gateway_pid" >/dev/null 2>&1 || true; wait "$gateway_pid" >/dev/null 2>&1 || true; }; rm -rf "$workdir"; exit "$status"; }
trap cleanup EXIT
[[ -f "$root/.env" && -f "$root/.governance-provision.env" ]] || { echo 'Missing local lab environment. Run npm run demo:env and npm run demo:seed first.' >&2; exit 1; }
set -a; source "$root/.env"; source "$root/.governance-provision.env"; set +a
container="$("${compose[@]}" ps -q postgres)"; [[ -n "$container" ]] || { echo 'PostgreSQL lab container is not running.' >&2; exit 1; }
docker exec "$container" createdb -U "$POSTGRES_USER" enterprise_mcp_governed_provisioning_v2 >/dev/null 2>&1 || true
address="$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$container")"
database_url="$(PGUSER="$POSTGRES_USER" PGPASSWORD="$POSTGRES_PASSWORD" PGDATABASE="$database" PGHOST="$address" node -e 'process.stdout.write(`postgresql://${encodeURIComponent(process.env.PGUSER)}:${encodeURIComponent(process.env.PGPASSWORD)}@${process.env.PGHOST}:5432/${encodeURIComponent(process.env.PGDATABASE)}`)')"
npm run build --prefix "$repo" >/dev/null
start_gateway(){
  if curl -sS -o /dev/null "http://127.0.0.1:$port/" 2>/dev/null; then echo "Port $port is already in use." >&2; exit 1; fi
  GOVERNANCE_OIDC_ISSUER="$issuer" GOVERNANCE_OIDC_JWKS_URL="$issuer/protocol/openid-connect/certs" GOVERNANCE_OIDC_AUDIENCE=enterprise-mcp-kit GOVERNANCE_STORAGE_BACKEND=postgres GOVERNANCE_DATABASE_URL="$database_url" GOVERNANCE_ALLOW_INSECURE_LOOPBACK_OIDC=true GOVERNANCE_PROVISIONING_ENABLED=true GOVERNANCE_ALLOW_INSECURE_LOOPBACK_WRITE=true NETBOX_PROVISION_BASE_URL="$NETBOX_PROVISION_BASE_URL" NETBOX_PROVISION_TOKEN="$NETBOX_PROVISION_TOKEN" NETBOX_PROVISION_TIMEOUT_MS="$NETBOX_PROVISION_TIMEOUT_MS" GOVERNANCE_HTTP_PORT="$port" node "$repo/dist/src/governance-http-server.js" >"$workdir/gateway.log" 2>&1 & gateway_pid=$!
  for _ in $(seq 1 30); do curl -sS -o /dev/null "http://127.0.0.1:$port/" 2>/dev/null && break; sleep 1; done
  kill -0 "$gateway_pid" 2>/dev/null || { cat "$workdir/gateway.log" >&2; exit 1; }
}
restart_gateway(){ kill "$gateway_pid" >/dev/null 2>&1 || true; wait "$gateway_pid" >/dev/null 2>&1 || true; gateway_pid=''; start_gateway; }
token(){ curl -fsS -X POST "$issuer/protocol/openid-connect/token" -d grant_type=password -d client_id=enterprise-mcp-kit -d "username=$1" -d password=local-demo-only | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>process.stdout.write(JSON.parse(s).access_token))'; }
planner="$(token northstar-planner)"; approver="$(token northstar-approver)"; executor="$(token northstar-executor)"; expires="$(node -e 'console.log(new Date(Date.now()+600000).toISOString())')"; suffix=$((run_id % 90 + 10)); slug="northstar-pg-governed-$run_id"; address_cidr="198.18.$suffix.253/32"; vid=$((3900 + run_id % 90))
payload="$(SITE_SLUG="$slug" VID="$vid" ADDRESS="$address_cidr" EXPIRES="$expires" node -e 'const e=process.env;process.stdout.write(JSON.stringify({manifest:{version:1,tenantSlug:"northstar-financial",site:{name:"Northstar PostgreSQL Governed "+e.SITE_SLUG,slug:e.SITE_SLUG,facility:"PG-GOV",physicalAddress:"Sanitized durable governance verification",timeZone:"America/Phoenix"},vlans:[{name:"PostgreSQL Governed VLAN",vid:Number(e.VID)}],prefixes:[{prefix:"198.18."+e.VID.slice(-2)+".0/24",vlanName:"PostgreSQL Governed VLAN",description:"Sanitized durable governance prefix"}],racks:[{name:"PG-G01",uHeight:42}],devices:[{name:"ns-pg-governed-edge-01",rackName:"PG-G01",position:42,face:"front",deviceTypeSlug:"edge-router-1000",roleSlug:"edge-router",platformSlug:null,interfaces:[{name:"ge-0/0/0",address:e.ADDRESS}]}]},proposedChange:"Create and roll back one PostgreSQL-backed governed provisioning manifest.",confidence:1,expiresAt:e.EXPIRES}))')"
start_gateway
plan_file="$workdir/plan.json"; plan_status="$(curl -sS -o "$plan_file" -w '%{http_code}' -X POST "http://127.0.0.1:$port/api/v1/governance/tools/plan_customer_site_provisioning" -H "Authorization: Bearer $planner" -H "Idempotency-Key: pg-$run_id-plan" -H 'content-type: application/json' --data "$payload")"; [[ "$plan_status" == 200 ]] || { echo "Durable planning failed with HTTP $plan_status: $(sed 's/[[:space:]]\+/ /g' "$plan_file")" >&2; exit 1; }; planned="$(cat "$plan_file")"
id="$(printf %s "$planned" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const x=JSON.parse(s);if(x.data?.state!=="planned"||x.data?.provisioning?.manifestDigest?.length!==64)process.exit(1);process.stdout.write(x.data.id)})')"
manifest_digest="$(printf %s "$planned" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>process.stdout.write(JSON.parse(s).data.provisioning.manifestDigest))')"
curl -fsS -X POST "http://127.0.0.1:$port/api/v1/governance/tools/approve_action_plan" -H "Authorization: Bearer $approver" -H "Idempotency-Key: pg-$run_id-approve" -H 'content-type: application/json' --data "{\"planId\":\"$id\",\"reason\":\"Durable PostgreSQL plan digest, tenant, and ordered resources reviewed.\"}" >/dev/null
for actor in "$planner" "$approver"; do denied_file="$workdir/denied.json"; status="$(curl -sS -o "$denied_file" -w '%{http_code}' -X POST "http://127.0.0.1:$port/api/v1/governance/tools/execute_action_plan" -H "Authorization: Bearer $actor" -H "Idempotency-Key: pg-$run_id-deny-$RANDOM" -H 'content-type: application/json' --data "{\"planId\":\"$id\"}")"; [[ "$status" == 401 ]] || { echo "Expected separation-of-duties denial, got $status: $(sed 's/[[:space:]]\+/ /g' "$denied_file")" >&2; exit 1; }; done
executed="$(curl -fsS -X POST "http://127.0.0.1:$port/api/v1/governance/tools/execute_action_plan" -H "Authorization: Bearer $executor" -H "Idempotency-Key: pg-$run_id-execute" -H 'content-type: application/json' --data "{\"planId\":\"$id\"}")"; printf %s "$executed" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const x=JSON.parse(s);if(x.data?.state!=="executed"||x.data.execution?.created?.length!==7)process.exit(1)})'
restart_gateway
replay="$(curl -fsS -X POST "http://127.0.0.1:$port/api/v1/governance/tools/execute_action_plan" -H "Authorization: Bearer $executor" -H "Idempotency-Key: pg-$run_id-execute" -H 'content-type: application/json' --data "{\"planId\":\"$id\"}")"; printf %s "$replay" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const x=JSON.parse(s);if(x.data?.state!=="executed"||x.meta?.replayed!==true)process.exit(1)})'
durable="$(curl -fsS -X POST "http://127.0.0.1:$port/api/v1/governance/tools/get_action_plan" -H "Authorization: Bearer $executor" -H 'content-type: application/json' --data "{\"planId\":\"$id\"}")"; printf %s "$durable" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{if(JSON.parse(s).data?.state!=="executed")process.exit(1)})'
audit="$(curl -fsS -X POST "http://127.0.0.1:$port/api/v1/governance/tools/list_audit_events" -H "Authorization: Bearer $executor" -H 'content-type: application/json' --data "{\"planId\":\"$id\"}")"; printf %s "$audit" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const x=JSON.parse(s),events=x.data?.events?.map(e=>e.event)??[];if(events.join(",")!=="plan_created,plan_approved,execution_started,execution_succeeded")process.exit(1)})'
rolled="$(curl -fsS -X POST "http://127.0.0.1:$port/api/v1/governance/tools/rollback_action_plan" -H "Authorization: Bearer $executor" -H "Idempotency-Key: pg-$run_id-rollback" -H 'content-type: application/json' --data "{\"planId\":\"$id\"}")"; printf %s "$rolled" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const x=JSON.parse(s);if(x.data?.state!=="rolled_back"||x.data.rollback?.compensated?.length!==7)process.exit(1)})'
restart_gateway
after="$(curl -fsS -X POST "http://127.0.0.1:$port/api/v1/governance/tools/get_action_plan" -H "Authorization: Bearer $executor" -H 'content-type: application/json' --data "{\"planId\":\"$id\"}")"; printf %s "$after" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{if(JSON.parse(s).data?.state!=="rolled_back")process.exit(1)})'
after_audit="$(curl -fsS -X POST "http://127.0.0.1:$port/api/v1/governance/tools/list_audit_events" -H "Authorization: Bearer $executor" -H 'content-type: application/json' --data "{\"planId\":\"$id\"}")"; printf %s "$after_audit" | MANIFEST_DIGEST="$manifest_digest" DATABASE_NAME="$database" node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{const x=JSON.parse(s),events=x.data?.events?.map(e=>e.event)??[];if(events.join(",")!=="plan_created,plan_approved,execution_started,execution_succeeded,rollback_started,rollback_succeeded")process.exit(1);console.log(JSON.stringify({governance_postgres_provisioning:"passed",database:process.env.DATABASE_NAME,planId:x.data.planId,manifestDigest:process.env.MANIFEST_DIGEST,stateAfterRestart:"rolled_back",auditEvents:events,replayAfterRestart:true,sourceDatabaseRetained:true,live_state_claim:false}))})'
