import assert from 'node:assert/strict';
import test from 'node:test';
import { GovernedIncidentWorkflow, incidentAction, type ObserverExecutor } from '../src/aiops-incident.js';
import { GovernanceAuthorizationError, GovernanceStateError, GovernanceValidationError } from '../src/governance.js';
const planner={subjectId:'planner',tenantId:'open-enterprise-aiops',roles:['planner']},approver={subjectId:'approver',tenantId:'open-enterprise-aiops',roles:['approver']},executorActor={subjectId:'executor',tenantId:'open-enterprise-aiops',roles:['executor']};
const now=()=>new Date('2026-08-12T05:00:00Z');
class Fake implements ObserverExecutor{pid=101;active=true;isHealthy=true;async snapshot(){return{active:this.active,mainPid:this.pid}}async restart(){this.pid=202}async healthy(){return this.isHealthy}}
const evidence=[{source:'prometheus' as const,observedAt:'2026-08-12T04:59:55Z',healthy:false,summary:'Observer availability is degraded.',decisionTraceId:'dtr_wireguard_netns_v1'},{source:'zabbix' as const,observedAt:'2026-08-12T04:59:56Z',healthy:false,summary:'Service availability trigger is active.',decisionTraceId:'dtr_wireguard_netns_v1'}];
test('requires distinct planner approver and executor then verifies exact restart',async()=>{const workflow=new GovernedIncidentWorkflow(new Fake(),now,()=> 'incident-1');let plan=await workflow.plan(planner,{expiresAt:'2026-08-12T05:10:00Z',confidence:.9,promptVersion:'incident-explainer-v1',evidence});assert.equal(plan.action,incidentAction);assert.equal(plan.state,'planned');assert.match(plan.approvalDigest,/^[a-f0-9]{64}$/);assert.throws(()=>workflow.approve(planner,plan,'self',plan.approvalDigest),GovernanceAuthorizationError);plan=workflow.approve(approver,plan,'Reviewed bounded evidence.',plan.approvalDigest);await assert.rejects(()=>workflow.execute(approver,plan),GovernanceAuthorizationError);plan=await workflow.execute(executorActor,plan);assert.equal(plan.state,'verified');assert.equal(plan.outcome?.afterPid,202);plan=await workflow.recordRollback(executorActor,plan,'No configuration changed; active state retained.');assert.equal(plan.state,'rollback_recorded');assert.deepEqual(plan.audit.map(x=>x.event),['plan_created','plan_approved','execution_started','execution_verified','rollback_state_recorded']);});
test('rejects stale, cross-trace, wrong-digest, and mutated plans',async()=>{const workflow=new GovernedIncidentWorkflow(new Fake(),now,()=> 'incident-2');await assert.rejects(()=>workflow.plan(planner,{expiresAt:'2026-08-12T05:20:00Z',confidence:.9,promptVersion:null,evidence}),GovernanceValidationError);await assert.rejects(()=>workflow.plan(planner,{expiresAt:'2026-08-12T05:10:00Z',confidence:.9,promptVersion:null,evidence:[...evidence.slice(0,1),{...evidence[1],decisionTraceId:'other'}]}),GovernanceValidationError);let plan=await workflow.plan(planner,{expiresAt:'2026-08-12T05:10:00Z',confidence:.9,promptVersion:null,evidence});assert.throws(()=>workflow.approve(approver,plan,'Approved.','0'.repeat(64)),GovernanceStateError);const digest=plan.approvalDigest;plan.evidence[0].summary='Mutated after review.';assert.throws(()=>workflow.approve(approver,plan,'Approved.',digest),GovernanceStateError);plan=await workflow.plan(planner,{expiresAt:'2026-08-12T05:10:00Z',confidence:.9,promptVersion:null,evidence});plan=workflow.approve(approver,plan,'Approved.',plan.approvalDigest);(plan as {action:string}).action='restart_any_service';await assert.rejects(()=>workflow.execute(executorActor,plan),GovernanceStateError);});
test('refuses remediation when every evidence source is healthy',async()=>{const workflow=new GovernedIncidentWorkflow(new Fake(),now);await assert.rejects(()=>workflow.plan(planner,{expiresAt:'2026-08-12T05:10:00Z',confidence:.9,promptVersion:null,evidence:evidence.map(item=>({...item,healthy:true}))}),GovernanceValidationError);});
test('fails closed when health verification does not recover',async()=>{const fake=new Fake();fake.isHealthy=false;const workflow=new GovernedIncidentWorkflow(fake,now,()=> 'incident-3');let plan=await workflow.plan(planner,{expiresAt:'2026-08-12T05:10:00Z',confidence:.8,promptVersion:null,evidence});plan=workflow.approve(approver,plan,'Reviewed.',plan.approvalDigest);plan=await workflow.execute(executorActor,plan);assert.equal(plan.state,'execution_failed');assert.equal(plan.outcome,null);});
