import assert from 'node:assert/strict';
import test from 'node:test';
import { planCustomerSiteProvisioning } from '../src/site-provisioning-manifest.js';
import { executeApprovedCustomerSiteProvisioning, type SiteProvisioningAdapter } from '../src/site-provisioning-executor.js';

const manifest={version:1 as const,tenantSlug:'northstar',site:{name:'Full Environment',slug:'full-environment',facility:'FULL-01',physicalAddress:'1 Example Way',timeZone:'UTC'},vlans:[{name:'App',vid:230}],prefixes:[{prefix:'10.23.0.0/24',vlanName:'App',description:'Application network'}],racks:[{name:'R1',uHeight:42}],devices:[{name:'leaf-a',rackName:'R1',position:42,face:'front' as const,deviceTypeSlug:'edge-router',roleSlug:'edge-router',platformSlug:null,interfaces:[{name:'xe-0/0/0',address:null}]},{name:'leaf-b',rackName:'R1',position:40,face:'front' as const,deviceTypeSlug:'edge-router',roleSlug:'edge-router',platformSlug:null,interfaces:[{name:'xe-0/0/0',address:null}]}],virtualMachines:[{name:'app-01',clusterName:'lab-cluster',vcpus:2,memoryMb:4096,diskGb:40,interfaces:[{name:'eth0',address:'10.23.0.10/24'}]}],power:{panels:[{name:'PP-1',description:'Main panel'}],feeds:[{name:'Feed-A',panelName:'PP-1',rackName:'R1',voltage:208,amperage:30}]},cables:[{name:'leaf-a-to-leaf-b',aDeviceName:'leaf-a',aInterfaceName:'xe-0/0/0',bDeviceName:'leaf-b',bInterfaceName:'xe-0/0/0'}],circuits:[{cid:'C-001',providerSlug:'carrier-a',typeSlug:'ethernet',commitRateKbps:1000000}],tunnels:[{name:'overlay-a',encapsulation:'vxlan' as const,tunnelId:230}]};
const discovery={tenantExists:async()=>true,siteExists:async()=>false,referencesExist:async()=>({missingDeviceTypes:[],missingRoles:[],missingPlatforms:[]}),addressesInUse:async()=>[],networkResourcesInUse:async()=>({vlanIds:[],prefixes:[]}),infrastructureReferencesExist:async()=>({missingClusters:[],missingProviders:[],missingCircuitTypes:[]})};
test('plans all bounded full-environment resource families before executing anything',async()=>{const dry=await planCustomerSiteProvisioning('northstar',manifest,discovery);assert.equal(dry.executable,true);assert.equal(dry.resourceCounts.virtualMachines,1);assert.equal(dry.resourceCounts.powerFeeds,1);assert.equal(dry.resourceCounts.cables,1);assert.equal(dry.resourceCounts.circuits,1);assert.equal(dry.resourceCounts.tunnels,1);});
test('creates full-environment records in dependency order and returns only their IDs for compensation',async()=>{let id=0;const adapter:SiteProvisioningAdapter={createSite:async()=>++id,createVlan:async()=>++id,createPrefix:async()=>++id,createRack:async()=>++id,createDevice:async()=>++id,createInterface:async()=>++id,createIpAddress:async()=>++id,createVirtualMachine:async()=>++id,createVmInterface:async()=>++id,createVmIpAddress:async()=>++id,createPowerPanel:async()=>++id,createPowerFeed:async()=>++id,createCircuit:async()=>++id,createTunnel:async()=>++id,createCable:async()=>++id,deleteCreated:async()=>{}};const dry=await planCustomerSiteProvisioning('northstar',manifest,discovery);const result=await executeApprovedCustomerSiteProvisioning({actorTenant:'northstar',approvedManifestDigest:dry.manifestDigest,manifest},discovery,adapter);assert.equal(result.state,'executed');assert.deepEqual(result.created.map(x=>x.kind),['site','vlan','prefix','rack','device','interface','device','interface','virtual-machine','vm-interface','ip-address','power-panel','power-feed','circuit','tunnel','cable']);});
