import assert from 'node:assert/strict';
import test from 'node:test';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { createNetBoxMcpServer } from '../src/mcp-server.js';
import { parseServerConfig } from '../src/server-config.js';
import { NetBoxClientConfigurationError, NetBoxRequestError, type ConnectivityPath, type DeviceContext, type NetBoxClient, type PowerPath, type RackContext, type SiteOverview } from '../src/netbox-client.js';

const token = 'test-token';
const device: DeviceContext = { id: 7, name: 'edge-01', status: 'active', site: null, role: 'router', deviceType: 'X1', platform: 'Example Network OS', observedSoftwareVersion: '12.4.3', minimumApprovedVersion: '12.4.0', versionCompliance: 'meets-example-policy', versionEvidenceSource: 'sanitized-lab-seed', versionObservedAt: '2026-07-28T12:00:00Z', primaryIpv4: null, primaryIpv6: null, source: 'api/dcim/devices/7/' };
const site: SiteOverview = { id: 2, name: 'Phoenix DC1', status: 'active', region: 'US West', tenant: 'Northstar', facility: 'PHX-DC1', deviceCount: 1, rackCount: 2, activeCircuitCount: 3, contactAssignmentCount: 1, softwareCompliantCount: 1, softwareNonCompliantCount: 0, softwareUnknownCount: 0, devices: [{ name: device.name, status: device.status, role: device.role, platform: device.platform, observedSoftwareVersion: device.observedSoftwareVersion, minimumApprovedVersion: device.minimumApprovedVersion, versionCompliance: device.versionCompliance }], truncated: false, source: 'api/dcim/sites/2/' };
const connectivity: ConnectivityPath = { fromSite: 'Northstar Phoenix DC1', toSite: 'Northstar Reno DR', segments: [{ kind: 'circuit', id: 2, name: 'EX-NS-DR-001', status: 'active', description: 'Private WAN', endpoints: [{ site: 'Northstar Phoenix DC1', device: 'ns-phx-edge-01', interface: 'ge-0/0/2', address: null }, { site: 'Northstar Reno DR', device: null, interface: null, address: null }], source: 'api/circuits/circuits/2/' }, { kind: 'vpn', id: 1, name: 'northstar-phoenix-to-reno', status: 'active', description: 'Encrypted overlay', endpoints: [{ site: 'Northstar Phoenix DC1', device: 'ns-phx-edge-01', interface: 'ge-0/0/2', address: '192.0.2.5/30' }, { site: 'Northstar Reno DR', device: 'ns-reno-edge-01', interface: 'ge-0/0/1', address: '192.0.2.6/30' }], source: 'api/vpn/tunnels/1/' }], completeness: 'direct-evidence', unknowns: ['NetBox evidence does not prove the runtime routed or forwarding path.'], truncated: false, source: 'NetBox read-only evidence' };
const rack: RackContext = { id: 1, name: 'PHX-A01', status: 'active', site: 'Northstar Phoenix DC1', location: 'Data Hall A', tenant: 'Northstar Financial', facilityId: null, role: null, widthInches: 19, heightUnits: 42, deviceCount: 1, powerFeedCount: 4, description: 'Production network and security', devices: [{ name: device.name, status: device.status, role: device.role, deviceType: device.deviceType, position: 42, face: 'front', platform: device.platform, primaryIpv4: device.primaryIpv4, observedSoftwareVersion: device.observedSoftwareVersion, versionCompliance: device.versionCompliance }], truncated: false, source: 'api/dcim/racks/1/' };
const powerPath: PowerPath = { device: { id: 7, name: 'edge-01', site: 'Northstar Phoenix DC1', rack: 'PHX-A01' }, powerPorts: [{ name: 'PSU-A', maximumDrawWatts: 600, allocatedDrawWatts: 300, connection: { pduDevice: 'pdu-a', outlet: 'A-01', feedLeg: 'A', source: 'api/dcim/power-ports/1/' } }, { name: 'PSU-B', maximumDrawWatts: 600, allocatedDrawWatts: 300, connection: { pduDevice: 'pdu-b', outlet: 'B-01', feedLeg: 'B', source: 'api/dcim/power-ports/2/' } }], recordedRackPowerFeeds: [{ id: 1, name: 'PHX-A01-FEED-A', status: 'active', type: 'primary', source: 'api/dcim/power-feeds/1/' }, { id: 2, name: 'PHX-A01-FEED-B', status: 'active', type: 'redundant', source: 'api/dcim/power-feeds/2/' }], redundancy: 'a-b-evidenced', unknowns: ['NetBox inventory evidence does not prove live electrical state, load, breaker state, or power delivery.'], truncated: false, source: 'api/dcim/devices/7/' };
function adapter(getDeviceContext: NetBoxClient['getDeviceContext'] = async () => device, getSiteOverview: NetBoxClient['getSiteOverview'] = async () => site, getConnectivityPath: NetBoxClient['getConnectivityPath'] = async () => connectivity, getRackContext: NetBoxClient['getRackContext'] = async () => rack, getPowerPath: NetBoxClient['getPowerPath'] = async () => powerPath): NetBoxClient { return { getDeviceContext, getSiteOverview, getConnectivityPath, getRackContext, getPowerPath }; }
async function connected(adapter: NetBoxClient) { const server = createNetBoxMcpServer(adapter); const client = new Client({ name: 'test', version: '1' }); const [a, b] = InMemoryTransport.createLinkedPair(); await Promise.all([server.connect(a), client.connect(b)]); return { client, server }; }
async function withConnection(adapter: NetBoxClient, run: (connection: Awaited<ReturnType<typeof connected>>) => Promise<void>) { const connection = await connected(adapter); try { await run(connection); } finally { await connection.client.close(); await connection.server.close(); } }
test('registers exactly five bounded read-only tools', async () => withConnection(adapter(), async ({ client }) => { const tools = await client.listTools(); assert.deepEqual(tools.tools.map((tool) => tool.name).sort(), ['get_connectivity_path', 'get_device_context', 'get_power_path', 'get_rack_context', 'get_site_overview']); for (const tool of tools.tools) assert.match(tool.description ?? '', /no write operations/i); }));
test('calls device adapter with parsed name and ID and returns only approved fields', async () => { const calls: unknown[] = []; await withConnection(adapter(async (input) => { calls.push(input); return device; }), async ({ client }) => { for (const arguments_ of [{ name: 'edge-01' }, { id: 7 }]) { const result = await client.callTool({ name: 'get_device_context', arguments: arguments_ }) as any; assert.notEqual(result.isError, true); assert.deepEqual(Object.keys(result.structuredContent).sort(), Object.keys(device).sort()); assert.deepEqual(result.structuredContent, device); assert.match(result.content[0].text, /observed software: 12\.4\.3/); assert.match(result.content[0].text, /minimum approved: 12\.4\.0/); assert.match(result.content[0].text, /unavailable/); } }); assert.deepEqual(calls, [{ name: 'edge-01' }, { id: 7 }]); });
test('returns bounded site overview with software posture', async () => withConnection(adapter(), async ({ client }) => { const result = await client.callTool({ name: 'get_site_overview', arguments: { name: 'Phoenix DC1' } }) as any; assert.notEqual(result.isError, true); assert.deepEqual(result.structuredContent, site); assert.match(result.content[0].text, /devices: 1/); assert.match(result.content[0].text, /software compliant: 1/); }));
test('returns evidence-bounded connectivity without claiming a routed path', async () => withConnection(adapter(), async ({ client }) => { const result = await client.callTool({ name: 'get_connectivity_path', arguments: { fromSite: connectivity.fromSite, toSite: connectivity.toSite } }) as any; assert.notEqual(result.isError, true); assert.deepEqual(result.structuredContent, connectivity); assert.match(result.content[0].text, /EX-NS-DR-001/); assert.match(result.content[0].text, /does not prove/i); }));
test('returns a bounded rack elevation summary', async () => withConnection(adapter(), async ({ client }) => { const result = await client.callTool({ name: 'get_rack_context', arguments: { site: rack.site, name: rack.name } }) as any; assert.notEqual(result.isError, true); assert.deepEqual(result.structuredContent, rack); assert.match(result.content[0].text, /42U/); assert.match(result.content[0].text, /power feeds: 4/); }));
test('returns bounded power evidence without claiming live state', async () => withConnection(adapter(), async ({ client }) => { const result = await client.callTool({ name: 'get_power_path', arguments: { name: 'edge-01' } }) as any; assert.notEqual(result.isError, true); assert.deepEqual(result.structuredContent, powerPath); assert.match(result.content[0].text, /a-b-evidenced/); assert.match(result.content[0].text, /does not prove live electrical state/i); }));
for (const arguments_ of [{}, { name: 'x', id: 1 }, { name: '' }, { name: ' x' }, { name: '*' }, { id: 0 }, { id: '7' }, { name: 'x', extra: true }]) test(`returns safe error for invalid input ${JSON.stringify(arguments_)}`, async () => { let calls = 0; await withConnection(adapter(async () => { calls++; return device; }), async ({ client }) => { const result = await client.callTool({ name: 'get_device_context', arguments: arguments_ }) as any; assert.equal(result.isError, true); const text = result.content[0].text as string; assert.match(text, /(name|id|input|exactly)/i); assert.doesNotMatch(text, /test-token|raw-body|stack/i); }); assert.equal(calls, 0); });
test('maps known and unknown adapter errors safely', async () => { await withConnection(adapter(async () => { throw new NetBoxRequestError('NetBox device was not found.'); }), async ({ client }) => { const result = await client.callTool({ name: 'get_device_context', arguments: { id: 7 } }) as any; assert.equal(result.isError, true); assert.match(result.content[0].text, /not found/); }); await withConnection(adapter(async () => { throw new Error('test-token raw-body stack'); }), async ({ client }) => { const result = await client.callTool({ name: 'get_device_context', arguments: { id: 7 } }) as any; assert.equal(result.isError, true); assert.equal(result.content[0].text, 'NetBox lookup failed.'); }); });
test('parses required server configuration without exposing tokens', () => { assert.deepEqual(parseServerConfig({ NETBOX_BASE_URL: 'http://netbox.lab.test', NETBOX_TOKEN: token, NETBOX_TIMEOUT_MS: '10' }), { baseUrl: 'http://netbox.lab.test', token, timeoutMs: 10 }); for (const env of [{ NETBOX_TOKEN: token }, { NETBOX_BASE_URL: 'http://netbox.lab.test' }, { NETBOX_BASE_URL: 'http://netbox.lab.test', NETBOX_TOKEN: token, NETBOX_TIMEOUT_MS: 'bad' }]) assert.throws(() => parseServerConfig(env), (error: Error) => error instanceof NetBoxClientConfigurationError && !error.message.includes(token)); });
