import assert from 'node:assert/strict';
import test from 'node:test';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { createNetBoxMcpServer } from '../src/mcp-server.js';
import { parseServerConfig } from '../src/server-config.js';
import { NetBoxClientConfigurationError, NetBoxRequestError, type DeviceContext, type NetBoxClient } from '../src/netbox-client.js';

const token = 'test-token';
const device: DeviceContext = { id: 7, name: 'edge-01', status: 'active', site: null, role: 'router', deviceType: 'X1', primaryIpv4: null, primaryIpv6: null, source: 'api/dcim/devices/7/' };
async function connected(adapter: NetBoxClient) { const server = createNetBoxMcpServer(adapter); const client = new Client({ name: 'test', version: '1' }); const [a, b] = InMemoryTransport.createLinkedPair(); await Promise.all([server.connect(a), client.connect(b)]); return { client, server }; }
async function withConnection(adapter: NetBoxClient, run: (connection: Awaited<ReturnType<typeof connected>>) => Promise<void>) { const connection = await connected(adapter); try { await run(connection); } finally { await connection.client.close(); await connection.server.close(); } }
test('registers exactly one bounded read-only tool', async () => withConnection({ getDeviceContext: async () => device }, async ({ client }) => { const tools = await client.listTools(); assert.equal(tools.tools.length, 1); assert.equal(tools.tools[0].name, 'get_device_context'); assert.match(tools.tools[0].description ?? '', /no write operations/i); }));
test('calls adapter with parsed name and ID and returns only approved fields', async () => { const calls: unknown[] = []; await withConnection({ getDeviceContext: async (input) => { calls.push(input); return device; } }, async ({ client }) => { for (const arguments_ of [{ name: 'edge-01' }, { id: 7 }]) { const result = await client.callTool({ name: 'get_device_context', arguments: arguments_ }) as any; assert.notEqual(result.isError, true); assert.deepEqual(Object.keys(result.structuredContent).sort(), Object.keys(device).sort()); assert.deepEqual(result.structuredContent, device); assert.match(result.content[0].text, /unavailable/); } }); assert.deepEqual(calls, [{ name: 'edge-01' }, { id: 7 }]); });
for (const arguments_ of [{}, { name: 'x', id: 1 }, { name: '' }, { name: ' x' }, { name: '*' }, { id: 0 }, { id: '7' }, { name: 'x', extra: true }]) test(`returns safe error for invalid input ${JSON.stringify(arguments_)}`, async () => { let calls = 0; await withConnection({ getDeviceContext: async () => { calls++; return device; } }, async ({ client }) => { const result = await client.callTool({ name: 'get_device_context', arguments: arguments_ }) as any; assert.equal(result.isError, true); const text = result.content[0].text as string; assert.match(text, /(name|id|input|exactly)/i); assert.doesNotMatch(text, /test-token|raw-body|stack/i); }); assert.equal(calls, 0); });
test('maps known and unknown adapter errors safely', async () => { await withConnection({ getDeviceContext: async () => { throw new NetBoxRequestError('NetBox device was not found.'); } }, async ({ client }) => { const result = await client.callTool({ name: 'get_device_context', arguments: { id: 7 } }) as any; assert.equal(result.isError, true); assert.match(result.content[0].text, /not found/); }); await withConnection({ getDeviceContext: async () => { throw new Error('test-token raw-body stack'); } }, async ({ client }) => { const result = await client.callTool({ name: 'get_device_context', arguments: { id: 7 } }) as any; assert.equal(result.isError, true); assert.equal(result.content[0].text, 'NetBox lookup failed.'); }); });
test('parses required server configuration without exposing tokens', () => { assert.deepEqual(parseServerConfig({ NETBOX_BASE_URL: 'http://netbox.lab.test', NETBOX_TOKEN: token, NETBOX_TIMEOUT_MS: '10' }), { baseUrl: 'http://netbox.lab.test', token, timeoutMs: 10 }); for (const env of [{ NETBOX_TOKEN: token }, { NETBOX_BASE_URL: 'http://netbox.lab.test' }, { NETBOX_BASE_URL: 'http://netbox.lab.test', NETBOX_TOKEN: token, NETBOX_TIMEOUT_MS: 'bad' }]) assert.throws(() => parseServerConfig(env), (error: Error) => error instanceof NetBoxClientConfigurationError && !error.message.includes(token)); });
