import assert from 'node:assert/strict';
import test from 'node:test';
import { DeviceLookupValidationError, HttpNetBoxClient, NetBoxClientConfigurationError, NetBoxRequestError, validateDeviceLookup } from '../src/netbox-client.js';

const token = 'test-token';
const device = { id: 7, name: 'edge-01', status: { value: 'active' }, site: { name: 'lab' }, role: { name: 'router' }, device_type: { model: 'X1' }, primary_ip4: { address: '192.0.2.7/24' }, primary_ip6: { address: '2001:db8::7/64' }, url: 'https://netbox.example/api/dcim/devices/7/' };
function client(response: Response | Promise<Response>, capture?: RequestInit[]): HttpNetBoxClient { return new HttpNetBoxClient({ baseUrl: 'https://netbox.example/', token, fetch: async (_url, init) => { capture?.push(init!); return response; } }); }

test('accepts HTTP and HTTPS lab client configuration', () => { for (const baseUrl of ['http://netbox.lab.test:8000', 'https://netbox.example']) assert.ok(new HttpNetBoxClient({ baseUrl, token, timeoutMs: 1, fetch: async () => new Response('{}') })); });
for (const [label, options] of [
  ['empty token', { baseUrl: 'https://netbox.example', token: '' }], ['padded token', { baseUrl: 'https://netbox.example', token: ` ${token}` }],
  ['zero timeout', { baseUrl: 'https://netbox.example', token, timeoutMs: 0 }], ['fractional timeout', { baseUrl: 'https://netbox.example', token, timeoutMs: 1.5 }], ['infinite timeout', { baseUrl: 'https://netbox.example', token, timeoutMs: Infinity }], ['string timeout', { baseUrl: 'https://netbox.example', token, timeoutMs: '1' }],
  ['FTP URL', { baseUrl: 'ftp://netbox.example', token }], ['credential URL', { baseUrl: `https://user:${token}@netbox.example`, token }], ['malformed URL', { baseUrl: 'not a URL', token }], ['non-callable fetch', { baseUrl: 'https://netbox.example', token, fetch: 1 }]
] as const) test(`rejects ${label} configuration without exposing token`, () => assert.throws(() => new HttpNetBoxClient(options as never), (error: Error) => error instanceof NetBoxClientConfigurationError && !error.message.includes(token)));

test('validates name and ID inputs', () => { assert.deepEqual(validateDeviceLookup({ name: 'edge-01' }), { name: 'edge-01' }); assert.deepEqual(validateDeviceLookup({ id: 7 }), { id: 7 }); });
for (const value of [{}, { name: 'x', id: 1 }, { name: '' }, { name: ' x' }, { name: 'x ' }, { name: '*' }, { name: ['x'] }, { name: 7 }, { id: 0 }, { id: 1.2 }, { id: '1' }, [], null]) test(`rejects invalid input ${JSON.stringify(value)}`, () => assert.throws(() => validateDeviceLookup(value), DeviceLookupValidationError));
test('uses GET-only exact endpoints and maps approved fields', async () => { const calls: RequestInit[] = []; let seen = ''; const adapter = new HttpNetBoxClient({ baseUrl: 'https://netbox.example/', token, fetch: async (url, init) => { seen = String(url); calls.push(init!); return new Response(JSON.stringify(device), { status: 200 }); } }); const result = await adapter.getDeviceContext({ id: 7 }); assert.equal(seen, 'https://netbox.example/api/dcim/devices/7/'); assert.equal(calls[0].method, 'GET'); assert.deepEqual(result, { id: 7, name: 'edge-01', status: 'active', site: 'lab', role: 'router', deviceType: 'X1', primaryIpv4: '192.0.2.7/24', primaryIpv6: '2001:db8::7/64', source: device.url }); });
test('uses encoded name endpoint and rejects missing or ambiguous results', async () => { let seen = ''; const ok = new HttpNetBoxClient({ baseUrl: 'https://netbox.example', token, fetch: async (url) => { seen = String(url); return new Response(JSON.stringify({ results: [device] })); } }); await ok.getDeviceContext({ name: 'edge-01' }); assert.equal(seen, 'https://netbox.example/api/dcim/devices/?name=edge-01'); for (const results of [[], [device, device]]) await assert.rejects(client(new Response(JSON.stringify({ results }))).getDeviceContext({ name: 'edge-01' }), NetBoxRequestError); });
for (const [status, message] of [[401, 'authenticated'], [403, 'authorized'], [404, 'not found'], [429, 'rate limited'], [500, 'unavailable']] as const) test(`maps HTTP ${status} without secrets`, async () => { await assert.rejects(client(new Response('raw-body', { status })).getDeviceContext({ id: 7 }), (error: Error) => error.message.includes(message) && !error.message.includes(token) && !error.message.includes('raw-body')); });
test('maps malformed JSON, timeout, and network errors without secrets', async () => { await assert.rejects(client(new Response('{', { status: 200 })).getDeviceContext({ id: 7 }), /invalid JSON/); const timed = new HttpNetBoxClient({ baseUrl: 'https://netbox.example', token, timeoutMs: 1, fetch: async (_url, init) => new Promise((_resolve, reject) => init?.signal?.addEventListener('abort', () => reject(Object.assign(new Error(), { name: 'AbortError' })))) }); await assert.rejects(timed.getDeviceContext({ id: 7 }), /timed out/); await assert.rejects(new HttpNetBoxClient({ baseUrl: 'https://netbox.example', token, fetch: async () => { throw new Error('raw-body ' + token); } }).getDeviceContext({ id: 7 }), (error: Error) => error.message === 'NetBox request failed.'); });
