import assert from 'node:assert/strict';
import test from 'node:test';
import { generateKeyPairSync, sign } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path'; import { tmpdir } from 'node:os';
import { GovernanceGateway } from '../src/governance-gateway.js'; import { FileGovernanceStore } from '../src/governance-storage.js'; import { OidcJwksVerifier } from '../src/oidc-jwks.js';
import { GovernanceAuthorizationError } from '../src/governance.js';
const issuer = 'https://issuer.example'; const audience = 'enterprise-mcp-kit'; const now = () => new Date('2026-07-29T12:00:00Z');
function token(kid = 'key-1', subject = 'planner', authorizedParty = audience): { token: string; jwk: Record<string, unknown> } { const { privateKey, publicKey } = generateKeyPairSync('rsa', { modulusLength: 2048 }); const header = Buffer.from(JSON.stringify({ alg: 'RS256', typ: 'JWT', kid })).toString('base64url'); const payload = Buffer.from(JSON.stringify({ iss: issuer, aud: audience, azp: authorizedParty, sub: subject, tenant_id: 'northstar', roles: ['planner'], iat: 1785326400, exp: 1785327000, jti: `jti-${kid}` })).toString('base64url'); return { token: `${header}.${payload}.${sign('RSA-SHA256', Buffer.from(`${header}.${payload}`), privateKey).toString('base64url')}`, jwk: { ...publicKey.export({ format: 'jwk' }), kid, use: 'sig' } }; }
test('verifies JWKS signed tokens and durably deduplicates concurrent dry-run plans', async () => { const keys = token(); const verifier = new OidcJwksVerifier({ issuer, audience, jwksUrl: 'https://issuer.example/keys', now, fetch: async () => new Response(JSON.stringify({ keys: [keys.jwk] })) }); const folder = await mkdtemp(join(tmpdir(), 'enterprise-mcp-kit-')); try { const store = new FileGovernanceStore(join(folder, 'governance.json')); const gateway = new GovernanceGateway({ verifier, store, issuer, audience, now }); const input = { actionType: 'netbox.device.update', target: { kind: 'netbox-device', id: '7' }, proposedChange: 'Change role.', confidence: 0.8, evidence: [{ source: 'api/dcim/devices/7/', summary: 'Current role.' }], ruleVersion: 'v1', promptVersion: null, expiresAt: '2026-07-29T12:10:00.000Z' }; const result = await gateway.invoke(`Bearer ${keys.token}`, 'create_action_plan', input, 'create-plan-0001'); const replay = await gateway.invoke(`Bearer ${keys.token}`, 'create_action_plan', input, 'create-plan-0001'); assert.equal(result.data.initiatedBy, 'planner'); assert.equal(result.meta.execution, 'disabled'); assert.equal(replay.data.id, result.data.id); assert.equal(replay.meta.replayed, true); await assert.rejects(gateway.invoke(`Bearer ${keys.token}`, 'create_action_plan', { ...input, proposedChange: 'Different.' }, 'create-plan-0001'), /different request/); await Promise.all([gateway.invoke(`Bearer ${keys.token}`, 'create_action_plan', { ...input, target: { ...input.target, id: '8' } }, 'create-plan-0002'), gateway.invoke(`Bearer ${keys.token}`, 'create_action_plan', { ...input, target: { ...input.target, id: '9' } }, 'create-plan-0003')]); const snapshot = await store.load(); assert.equal(snapshot.plans.length, 3); assert.equal(snapshot.receipts.length, 3); } finally { await rm(folder, { recursive: true, force: true }); } });
test('accepts a rotated signing key and rejects stale or wrong-client tokens', async () => {
  const first = token('key-1'); const rotated = token('key-2'); let keys = [first.jwk];
  const verifier = new OidcJwksVerifier({ issuer, audience, jwksUrl: 'https://issuer.example/keys', now, fetch: async () => new Response(JSON.stringify({ keys })) });
  await verifier.verify(first.token); keys = [rotated.jwk]; await verifier.verify(rotated.token);
  const wrongClient = token('key-3', 'planner', 'other-client'); keys = [wrongClient.jwk];
  await assert.rejects(verifier.verify(wrongClient.token), GovernanceAuthorizationError);
});
