import assert from 'node:assert/strict';
import test from 'node:test';
import { generateKeyPairSync, sign } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path'; import { tmpdir } from 'node:os';
import { GovernanceGateway } from '../src/governance-gateway.js'; import { FileGovernanceStore } from '../src/governance-storage.js'; import { OidcJwksVerifier } from '../src/oidc-jwks.js';
const issuer = 'https://issuer.example'; const audience = 'enterprise-mcp-kit'; const now = () => new Date('2026-07-29T12:00:00Z');
function token(): { token: string; jwk: Record<string, unknown> } { const { privateKey, publicKey } = generateKeyPairSync('rsa', { modulusLength: 2048 }); const header = Buffer.from(JSON.stringify({ alg: 'RS256', kid: 'key-1' })).toString('base64url'); const payload = Buffer.from(JSON.stringify({ iss: issuer, aud: audience, sub: 'planner', tenant_id: 'northstar', roles: ['planner'], exp: 1785327000 })).toString('base64url'); return { token: `${header}.${payload}.${sign('RSA-SHA256', Buffer.from(`${header}.${payload}`), privateKey).toString('base64url')}`, jwk: { ...publicKey.export({ format: 'jwk' }), kid: 'key-1', use: 'sig' } }; }
test('verifies JWKS signed tokens and persists an authenticated dry-run plan', async () => { const keys = token(); const verifier = new OidcJwksVerifier({ issuer, audience, jwksUrl: 'https://issuer.example/keys', now, fetch: async () => new Response(JSON.stringify({ keys: [keys.jwk] })) }); const folder = await mkdtemp(join(tmpdir(), 'enterprise-mcp-kit-')); try { const gateway = new GovernanceGateway({ verifier, store: new FileGovernanceStore(join(folder, 'governance.json')), issuer, audience, now }); const result = await gateway.invoke(`Bearer ${keys.token}`, 'create_action_plan', { actionType: 'netbox.device.update', target: { kind: 'netbox-device', id: '7' }, proposedChange: 'Change role.', confidence: 0.8, evidence: [{ source: 'api/dcim/devices/7/', summary: 'Current role.' }], ruleVersion: 'v1', promptVersion: null, expiresAt: '2026-07-29T12:10:00.000Z' }); assert.equal(result.data.initiatedBy, 'planner'); assert.equal(result.meta.execution, 'disabled'); } finally { await rm(folder, { recursive: true, force: true }); } });
