#!/bin/sh
set -eu
test "$(id -u)" -eq 0 || { echo 'Run as WSL root.' >&2; exit 1; }
cd "$(dirname "$0")/../.."
pod=aiops-f1-high-cpu; namespace=cloud-reference; trace=dtr_kubernetes_f1_v1; evidence_dir=delivery-evidence/kubernetes; evidence_path="$evidence_dir/f1-high-cpu.json"; started_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
cleanup(){ k3s kubectl -n "$namespace" delete pod "$pod" --ignore-not-found --wait=true >/dev/null 2>&1||true; }
trap cleanup EXIT INT TERM
cleanup
k3s kubectl -n "$namespace" run "$pod" --image='docker.io/nginxinc/nginx-unprivileged@sha256:27985295bdb22a1ef8f712863210bd5877c0f3006494a593e86b3fe0fa55467e' --restart=Never --labels="app=aiops-f1-high-cpu,aiops.site=las,decision-trace-id=$trace" --overrides='{"spec":{"automountServiceAccountToken":false,"securityContext":{"runAsNonRoot":true,"seccompProfile":{"type":"RuntimeDefault"}},"containers":[{"name":"aiops-f1-high-cpu","image":"docker.io/nginxinc/nginx-unprivileged@sha256:27985295bdb22a1ef8f712863210bd5877c0f3006494a593e86b3fe0fa55467e","command":["/bin/sh","-c","while :; do :; done"],"resources":{"requests":{"cpu":"150m","memory":"16Mi"},"limits":{"cpu":"200m","memory":"32Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"readOnlyRootFilesystem":true,"capabilities":{"drop":["ALL"]}}}]}}' >/dev/null
k3s kubectl -n "$namespace" wait --for=condition=Ready "pod/$pod" --timeout=120s >/dev/null
deadline=$(($(date +%s)+120)); alert_started_at=''; cpu=0
while test "$(date +%s)" -lt "$deadline"; do cpu="$(curl -fsS 'http://127.0.0.1:9090/api/v1/query?query=aiops_kubernetes_pod_cpu_millicores%7Bpod%3D%22aiops-f1-high-cpu%22%7D'|jq -r '.data.result[0].value[1] // 0')"; firing="$(curl -fsS 'http://127.0.0.1:9090/api/v1/alerts'|jq -r '[.data.alerts[]|select(.labels.alertname=="KubernetesLasPodHighCpu" and .state=="firing")]|length')"; if awk "BEGIN{exit !($cpu>=100)}"&&test "$firing" -gt 0;then alert_started_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)";break;fi;sleep 5;done
test -n "$alert_started_at"; cleanup
recovery_deadline=$(($(date +%s)+60)); while test "$(date +%s)" -lt "$recovery_deadline";do firing="$(curl -fsS 'http://127.0.0.1:9090/api/v1/alerts'|jq -r '[.data.alerts[]|select(.labels.alertname=="KubernetesLasPodHighCpu" and .state=="firing")]|length')";test "$firing" -eq 0&&break;sleep 5;done;test "$firing" -eq 0;recovered_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
mkdir -p "$evidence_dir";STARTED_AT="$started_at" ALERT_STARTED_AT="$alert_started_at" RECOVERED_AT="$recovered_at" CPU="$cpu" TRACE="$trace" node --input-type=module -e 'import{writeFileSync}from"node:fs";const e={schemaVersion:1,acceptanceTest:"AT-05",scenario:"F1-workload-high-cpu",result:"passed",decisionTraceId:process.env.TRACE,startedAt:process.env.STARTED_AT,alertFiringAt:process.env.ALERT_STARTED_AT,recoveredAt:process.env.RECOVERED_AT,observedCpuMillicores:Number(process.env.CPU),alert:"KubernetesLasPodHighCpu",site:"las",sourceOwner:"Kubernetes Metrics API via Prometheus",injectedPodRemoved:true,autonomousRemediation:false,boundary:"Single-node WSL K3s workload evidence; not physical-site HA."};writeFileSync("delivery-evidence/kubernetes/f1-high-cpu.json",`${JSON.stringify(e,null,2)}\n`,{mode:0o600});';sha256sum "$evidence_path">"$evidence_path.sha256";cat "$evidence_path";cat "$evidence_path.sha256"
