import { randomUUID } from 'node:crypto';
import type { IncomingMessage, ServerResponse } from 'node:http';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { GovernanceAuthorizationError, GovernanceValidationError } from './governance.js';
import { createGovernanceRemoteMcpServer } from './governance-remote-mcp.js';
import type { GovernanceGateway } from './governance-gateway.js';

export interface GovernanceRemoteHttpOptions{allowedHosts:string[];requestsPerMinute:number;bodyLimitBytes?:number;now?:()=>number;}
export function createGovernanceRemoteHttpHandler(gateway:GovernanceGateway,options:GovernanceRemoteHttpOptions){const limiter=new FixedWindowLimiter(options.requestsPerMinute,options.now);const bodyLimit=options.bodyLimitBytes??65_536;return async(request:IncomingMessage,response:ServerResponse)=>{const requestId=validRequestId(request.headers['x-request-id'])??randomUUID();response.setHeader('x-request-id',requestId);response.setHeader('cache-control','no-store');if(request.method!=='POST'||request.url!=='/mcp')return jsonRpc(response,405,'Method not allowed.');const authorization=request.headers.authorization;try{const actor=await gateway.authenticate(authorization);limiter.consume(`${actor.tenantId}:${actor.subjectId}`);const body=await readJson(request,bodyLimit);const server=createGovernanceRemoteMcpServer(gateway,authorization!);const transport=new StreamableHTTPServerTransport({sessionIdGenerator:undefined,enableJsonResponse:true,allowedHosts:options.allowedHosts,enableDnsRebindingProtection:true});await server.connect(transport);response.on('close',()=>{void transport.close();void server.close();});await transport.handleRequest(request,response,body);}catch(error){if(error instanceof GovernanceAuthorizationError)return jsonRpc(response,401,error.message);if(error instanceof GovernanceValidationError)return jsonRpc(response,400,error.message);return jsonRpc(response,429,error instanceof Error&&error.message==='Rate limit exceeded.'?error.message:'Governance MCP request failed.');}};}
class FixedWindowLimiter{private readonly windows=new Map<string,{start:number;count:number}>();constructor(private readonly limit:number,private readonly now:()=>number=Date.now){if(!Number.isInteger(limit)||limit<1||limit>10_000)throw new GovernanceValidationError('Remote MCP rate limit is invalid.');}consume(key:string){const time=this.now(),current=this.windows.get(key);if(!current||time-current.start>=60_000){this.windows.set(key,{start:time,count:1});return;}if(current.count>=this.limit)throw new Error('Rate limit exceeded.');current.count++;}}
async function readJson(request:IncomingMessage,limit:number){let body='';for await(const chunk of request){body+=chunk;if(Buffer.byteLength(body)>limit)throw new GovernanceValidationError('Request body exceeds the configured limit.');}try{return JSON.parse(body);}catch{throw new GovernanceValidationError('Request body must be valid JSON.');}}
function validRequestId(value:unknown){return typeof value==='string'&&/^[A-Za-z0-9._:-]{1,128}$/.test(value)?value:undefined;}
function jsonRpc(response:ServerResponse,status:number,message:string){if(response.headersSent)return;response.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});response.end(JSON.stringify({jsonrpc:'2.0',error:{code:status===401?-32001:status===429?-32002:-32600,message},id:null}));}
