import { createServer } from 'node:http';
import { parseGovernanceHttpConfig } from './governance-http-config.js';
import { createGovernanceHttpHandler, GovernanceGateway } from './governance-gateway.js';
import { FileGovernanceStore } from './governance-storage.js';
import { PostgresGovernanceStore } from './governance-postgres-storage.js';
import { OidcJwksVerifier } from './oidc-jwks.js';
import { NetBoxDeviceMetadataWriter } from './netbox-metadata-writer.js';
import { NetBoxSiteInformationWriter } from './netbox-site-writer.js';
import { NetBoxSiteProvisioningAdapter } from './netbox-site-provisioning-adapter.js';
import { NetBoxInventoryIntentWriter } from './netbox-inventory-intent-writer.js';
import { createGovernanceRemoteHttpHandler } from './governance-remote-http.js';
import { GovernanceMetrics,handleOperationalRoute,observeRequest } from './governance-observability.js';
const config = parseGovernanceHttpConfig(process.env);
const store=config.storageBackend==='postgres'?PostgresGovernanceStore.fromConnectionString(config.databaseUrl!):new FileGovernanceStore(config.storagePath);
const gateway = new GovernanceGateway({ issuer: config.issuer, audience: config.audience, verifier: new OidcJwksVerifier({ issuer: config.issuer, audience: config.audience, jwksUrl: config.jwksUrl, allowInsecureLoopback: config.allowInsecureLoopbackOidc }), store, writer: config.executionEnabled ? new NetBoxDeviceMetadataWriter({ baseUrl: config.netboxWriteBaseUrl!, token: config.netboxWriteToken! }) : undefined, siteWriter: config.executionEnabled ? new NetBoxSiteInformationWriter({ baseUrl: config.netboxWriteBaseUrl!, token: config.netboxWriteToken! }) : undefined, inventoryWriter: config.executionEnabled ? new NetBoxInventoryIntentWriter({ baseUrl: config.netboxWriteBaseUrl!, token: config.netboxWriteToken! }) : undefined, provisioningAdapter: config.provisioningEnabled ? new NetBoxSiteProvisioningAdapter({baseUrl:config.netboxProvisionBaseUrl!,token:config.netboxProvisionToken!,timeoutMs:config.netboxProvisionTimeoutMs}):undefined });
const rest=createGovernanceHttpHandler(gateway);const remoteMcp=createGovernanceRemoteHttpHandler(gateway,{allowedHosts:config.mcpAllowedHosts,requestsPerMinute:config.mcpRequestsPerMinute});
const metrics=new GovernanceMetrics();const server=createServer(async(request,response)=>{observeRequest(metrics,request,response);if(await handleOperationalRoute(request,response,store,metrics,config.storageBackend))return;return request.url==='/mcp'?remoteMcp(request,response):rest(request,response);});
server.listen(config.port, config.host, () => console.error(`Governance HTTP gateway listening on ${config.host}:${config.port}`));
