import { GovernanceValidationError } from './governance.js';
export interface GovernanceHttpConfig { host: string; port: number; issuer: string; audience: string; jwksUrl: string; storagePath: string; storageBackend:'file'|'postgres';databaseUrl?:string; allowInsecureLoopbackOidc: boolean; executionEnabled: boolean; provisioningEnabled: boolean; mcpAllowedHosts:string[];mcpRequestsPerMinute:number; netboxWriteBaseUrl?: string; netboxWriteToken?: string; netboxProvisionBaseUrl?: string; netboxProvisionToken?: string; netboxProvisionTimeoutMs?: number; }
export function parseGovernanceHttpConfig(env: NodeJS.ProcessEnv): GovernanceHttpConfig {
  const allowInsecureLoopbackOidc = env.GOVERNANCE_ALLOW_INSECURE_LOOPBACK_OIDC === 'true'; const issuer = requiredUrl(env.GOVERNANCE_OIDC_ISSUER, 'GOVERNANCE_OIDC_ISSUER', allowInsecureLoopbackOidc); const jwksUrl = requiredUrl(env.GOVERNANCE_OIDC_JWKS_URL, 'GOVERNANCE_OIDC_JWKS_URL', allowInsecureLoopbackOidc); const audience = exact(env.GOVERNANCE_OIDC_AUDIENCE, 'GOVERNANCE_OIDC_AUDIENCE'); const storageBackend=env.GOVERNANCE_STORAGE_BACKEND==='postgres'?'postgres':'file';const storagePath=storageBackend==='file'?exact(env.GOVERNANCE_STORAGE_PATH,'GOVERNANCE_STORAGE_PATH'):(env.GOVERNANCE_STORAGE_PATH??'postgres-managed');const databaseUrl=storageBackend==='postgres'?exact(env.GOVERNANCE_DATABASE_URL,'GOVERNANCE_DATABASE_URL'):undefined; const host = env.GOVERNANCE_HTTP_HOST ?? '127.0.0.1'; const port = Number(env.GOVERNANCE_HTTP_PORT ?? '8787');
  const executionEnabled = env.GOVERNANCE_EXECUTION_ENABLED === 'true'; let netboxWriteBaseUrl: string | undefined; let netboxWriteToken: string | undefined;
  if (executionEnabled) { netboxWriteBaseUrl = requiredUrl(env.NETBOX_WRITE_BASE_URL, 'NETBOX_WRITE_BASE_URL', env.GOVERNANCE_ALLOW_INSECURE_LOOPBACK_WRITE === 'true'); netboxWriteToken = exact(env.NETBOX_WRITE_TOKEN, 'NETBOX_WRITE_TOKEN'); }
  const provisioningEnabled=env.GOVERNANCE_PROVISIONING_ENABLED==='true';let netboxProvisionBaseUrl:string|undefined;let netboxProvisionToken:string|undefined;let netboxProvisionTimeoutMs:number|undefined;if(provisioningEnabled){netboxProvisionBaseUrl=requiredUrl(env.NETBOX_PROVISION_BASE_URL,'NETBOX_PROVISION_BASE_URL',env.GOVERNANCE_ALLOW_INSECURE_LOOPBACK_WRITE==='true');netboxProvisionToken=exact(env.NETBOX_PROVISION_TOKEN,'NETBOX_PROVISION_TOKEN');netboxProvisionTimeoutMs=Number(env.NETBOX_PROVISION_TIMEOUT_MS??'5000');if(!Number.isInteger(netboxProvisionTimeoutMs)||netboxProvisionTimeoutMs<1||netboxProvisionTimeoutMs>30000)throw new GovernanceValidationError('NETBOX_PROVISION_TIMEOUT_MS is invalid.');}
  const mcpAllowedHosts=(env.GOVERNANCE_MCP_ALLOWED_HOSTS??`${host}:${port}`).split(',').map(x=>x.trim()).filter(Boolean);const mcpRequestsPerMinute=Number(env.GOVERNANCE_MCP_REQUESTS_PER_MINUTE??'60');if(mcpAllowedHosts.length<1||mcpAllowedHosts.length>20||mcpAllowedHosts.some(x=>!/^[A-Za-z0-9.:[\]-]+(?::\d{1,5})?$/.test(x))||!Number.isInteger(mcpRequestsPerMinute)||mcpRequestsPerMinute<1||mcpRequestsPerMinute>10_000)throw new GovernanceValidationError('Remote MCP host protection or rate limit is invalid.');
  if (!/^[A-Za-z0-9.-]+$/.test(host) || !Number.isInteger(port) || port < 1 || port > 65535) throw new GovernanceValidationError('GOVERNANCE_HTTP_HOST and GOVERNANCE_HTTP_PORT are invalid.'); return { host, port, issuer, audience, jwksUrl, storagePath,storageBackend,databaseUrl, allowInsecureLoopbackOidc, executionEnabled, provisioningEnabled,mcpAllowedHosts,mcpRequestsPerMinute, netboxWriteBaseUrl, netboxWriteToken, netboxProvisionBaseUrl, netboxProvisionToken, netboxProvisionTimeoutMs };
}
function exact(value: string | undefined, name: string): string { if (!value || value.trim() !== value) throw new GovernanceValidationError(`${name} is required.`); return value; }
function requiredUrl(value: string | undefined, name: string, local: boolean): string { const text = exact(value, name); try { const url = new URL(text); if (url.protocol === 'https:' || (local && url.protocol === 'http:' && ['127.0.0.1', 'localhost', '::1'].includes(url.hostname))) return text; throw new Error(); } catch { throw new GovernanceValidationError(`${name} must be HTTPS, except explicit loopback lab mode.`); } }
