import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { GovernanceAuthorizationError, GovernanceStateError, GovernanceValidationError, type GovernanceActor, type InMemoryActionGovernance } from './governance.js';

export interface TrustedActorProvider { getActor(): GovernanceActor; }
const exact = z.string().min(1).refine((value) => value.trim() === value, 'Must be a non-empty exact string.');
const reconciliationStatus = z.enum(['matched', 'drifted', 'missing-observation', 'exception', 'not-evaluated']);
const versionValue = z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._+:-]{0,63}$/); const metadataField = z.enum(['reconciliation_status', 'observed_software_version', 'minimum_approved_version', 'physical_address', 'shipping_address', 'description', 'facility', 'time_zone']);
const operation = z.object({ field: metadataField, expectedValue: z.union([reconciliationStatus, versionValue]).nullable(), newValue: z.union([reconciliationStatus, versionValue]).nullable(), expectedLastUpdated: z.string().datetime() }).strict();
export const governancePlanInputSchema = z.object({ actionType: exact, target: z.object({ kind: exact, id: exact }).strict(), proposedChange: exact, confidence: z.number().min(0).max(1), evidence: z.array(z.object({ source: exact, summary: exact }).strict()).min(1).max(20), ruleVersion: exact, promptVersion: exact.nullable(), expiresAt: z.string().datetime(), operation: operation.nullable().optional() }).strict();
const resultFields = { tenantId: z.string(), field: metadataField, beforeValue: z.string().nullable(), afterValue: z.string().nullable(), beforeLastUpdated: z.string(), afterLastUpdated: z.string(), source: z.string() }; const writeResult = z.union([z.object({ deviceId: z.number().int().positive(), deviceName: z.string(), ...resultFields }).strict(), z.object({ siteId: z.number().int().positive(), siteName: z.string(), ...resultFields }).strict()]);
const execution = writeResult.and(z.object({ executedBy: z.string(), executedAt: z.string() }).strict()); const rollback = writeResult.and(z.object({ rolledBackBy: z.string(), rolledBackAt: z.string() }).strict());
const provisionedRecord=z.object({kind:z.enum(['site','vlan','prefix','rack','device','interface','ip-address']),id:z.number().int().positive(),key:z.string()}).strict();const provisioningExecution=z.object({manifestDigest:z.string().regex(/^[a-f0-9]{64}$/),state:z.enum(['executed','compensated','compensation_failed']),created:z.array(provisionedRecord),compensated:z.array(provisionedRecord),errors:z.array(z.string()),boundary:z.string()}).strict();
export const customerSiteManifestSchema=z.object({version:z.literal(1),tenantSlug:z.string(),site:z.object({name:z.string(),slug:z.string(),facility:z.string(),physicalAddress:z.string(),timeZone:z.string()}).strict(),vlans:z.array(z.object({name:z.string(),vid:z.number().int().min(1).max(4094)}).strict()).max(64).optional(),prefixes:z.array(z.object({prefix:z.string(),vlanName:z.string().nullable(),description:z.string()}).strict()).max(64).optional(),racks:z.array(z.object({name:z.string(),uHeight:z.number().int()}).strict()),devices:z.array(z.object({name:z.string(),rackName:z.string(),position:z.number().int(),face:z.enum(['front','rear']),deviceTypeSlug:z.string(),roleSlug:z.string(),platformSlug:z.string().nullable(),interfaces:z.array(z.object({name:z.string(),address:z.string().nullable()}).strict())}).strict())}).strict();const provisioning=z.object({manifest:customerSiteManifestSchema,manifestDigest:z.string().regex(/^[a-f0-9]{64}$/)}).strict();
const provisionExecution=provisioningExecution.and(z.object({executedBy:z.string(),executedAt:z.string()}).strict());const provisionRollback=provisioningExecution.and(z.object({rolledBackBy:z.string(),rolledBackAt:z.string()}).strict());
export const governancePlanOutputSchema = z.object({ id: z.string(), tenantId: z.string(), initiatedBy: z.string(), state: z.enum(['planned', 'approved', 'rejected', 'expired', 'executing', 'executed', 'execution_failed', 'rolling_back', 'rolled_back', 'rollback_failed']), createdAt: z.string(), approvedBy: z.string().nullable(), approvedAt: z.string().nullable(), approvalReason: z.string().nullable(), actionType: z.string(), target: z.object({ kind: z.string(), id: z.string() }).strict(), proposedChange: z.string(), confidence: z.number(), evidence: z.array(z.object({ source: z.string(), summary: z.string() }).strict()), ruleVersion: z.string(), promptVersion: z.string().nullable(), expiresAt: z.string(), operation: operation.nullable(), provisioning: provisioning.nullable(), execution: z.union([execution,provisionExecution]).nullable(), rollback: z.union([rollback,provisionRollback]).nullable() }).strict();
const planIdInput = z.object({ planId: exact }).strict();
const decisionInput = z.object({ planId: exact, reason: exact }).strict();
function safe(error: unknown): string { return error instanceof GovernanceValidationError || error instanceof GovernanceAuthorizationError || error instanceof GovernanceStateError ? error.message : 'Governance request failed.'; }

/**
 * Deliberately separate from the unauthenticated stdio NetBox server. The actor
 * is injected by a transport that has already authenticated the caller.
 */
export function createGovernanceMcpServer(governance: InMemoryActionGovernance, actors: TrustedActorProvider): McpServer {
  const server = new McpServer({ name: 'enterprise-mcp-kit-governance', version: '0.1.0' });
  const respond = (fn: () => unknown) => { try { const result = fn(); return { content: [{ type: 'text' as const, text: 'Governance state recorded; no external action was executed.' }], structuredContent: governancePlanOutputSchema.parse(result) }; } catch (error) { return { content: [{ type: 'text' as const, text: safe(error) }], isError: true }; } };
  server.registerTool('create_action_plan', { description: 'Create a tenant-scoped, evidence-backed, dry-run action plan. It never executes an external action.', inputSchema: governancePlanInputSchema, outputSchema: governancePlanOutputSchema }, (input) => respond(() => governance.createPlan(actors.getActor(), input as never)));
  server.registerTool('get_action_plan', { description: 'Read one tenant-scoped action plan. It never executes an external action.', inputSchema: planIdInput, outputSchema: governancePlanOutputSchema }, (input) => respond(() => governance.getPlan(actors.getActor(), input.planId)));
  server.registerTool('approve_action_plan', { description: 'Record a human approval for one unexpired action plan. It never executes an external action.', inputSchema: decisionInput, outputSchema: governancePlanOutputSchema }, (input) => respond(() => governance.approvePlan(actors.getActor(), input.planId, input.reason)));
  server.registerTool('reject_action_plan', { description: 'Record a human rejection for one unexpired action plan. It never executes an external action.', inputSchema: decisionInput, outputSchema: governancePlanOutputSchema }, (input) => respond(() => governance.rejectPlan(actors.getActor(), input.planId, input.reason)));
  return server;
}
