import { GovernanceValidationError } from './governance.js';
export interface GovernanceHttpConfig { host: string; port: number; issuer: string; audience: string; jwksUrl: string; storagePath: string; allowInsecureLoopbackOidc: boolean; executionEnabled: boolean; netboxWriteBaseUrl?: string; netboxWriteToken?: string; }
export function parseGovernanceHttpConfig(env: NodeJS.ProcessEnv): GovernanceHttpConfig {
  const allowInsecureLoopbackOidc = env.GOVERNANCE_ALLOW_INSECURE_LOOPBACK_OIDC === 'true'; const issuer = requiredUrl(env.GOVERNANCE_OIDC_ISSUER, 'GOVERNANCE_OIDC_ISSUER', allowInsecureLoopbackOidc); const jwksUrl = requiredUrl(env.GOVERNANCE_OIDC_JWKS_URL, 'GOVERNANCE_OIDC_JWKS_URL', allowInsecureLoopbackOidc); const audience = exact(env.GOVERNANCE_OIDC_AUDIENCE, 'GOVERNANCE_OIDC_AUDIENCE'); const storagePath = exact(env.GOVERNANCE_STORAGE_PATH, 'GOVERNANCE_STORAGE_PATH'); const host = env.GOVERNANCE_HTTP_HOST ?? '127.0.0.1'; const port = Number(env.GOVERNANCE_HTTP_PORT ?? '8787');
  const executionEnabled = env.GOVERNANCE_EXECUTION_ENABLED === 'true'; let netboxWriteBaseUrl: string | undefined; let netboxWriteToken: string | undefined;
  if (executionEnabled) { netboxWriteBaseUrl = requiredUrl(env.NETBOX_WRITE_BASE_URL, 'NETBOX_WRITE_BASE_URL', env.GOVERNANCE_ALLOW_INSECURE_LOOPBACK_WRITE === 'true'); netboxWriteToken = exact(env.NETBOX_WRITE_TOKEN, 'NETBOX_WRITE_TOKEN'); }
  if (!/^[A-Za-z0-9.-]+$/.test(host) || !Number.isInteger(port) || port < 1 || port > 65535) throw new GovernanceValidationError('GOVERNANCE_HTTP_HOST and GOVERNANCE_HTTP_PORT are invalid.'); return { host, port, issuer, audience, jwksUrl, storagePath, allowInsecureLoopbackOidc, executionEnabled, netboxWriteBaseUrl, netboxWriteToken };
}
function exact(value: string | undefined, name: string): string { if (!value || value.trim() !== value) throw new GovernanceValidationError(`${name} is required.`); return value; }
function requiredUrl(value: string | undefined, name: string, local: boolean): string { const text = exact(value, name); try { const url = new URL(text); if (url.protocol === 'https:' || (local && url.protocol === 'http:' && ['127.0.0.1', 'localhost', '::1'].includes(url.hostname))) return text; throw new Error(); } catch { throw new GovernanceValidationError(`${name} must be HTTPS, except explicit loopback lab mode.`); } }
