import { Pool, type PoolClient } from 'pg';
import { GovernanceValidationError, type GovernanceAuditEvent, type GovernanceSnapshot } from './governance.js';
import type { GovernanceStore } from './governance-storage.js';

const empty=():GovernanceSnapshot=>({version:2,plans:[],events:[],receipts:[]});
export class PostgresGovernanceStore implements GovernanceStore{
  private initialization:Promise<void>|undefined;
  constructor(private readonly pool:Pool){if(!pool)throw new GovernanceValidationError('PostgreSQL governance pool is required.');}
  static fromConnectionString(connectionString:string){if(!connectionString||connectionString.trim()!==connectionString)throw new GovernanceValidationError('GOVERNANCE_DATABASE_URL is required.');let url:URL;try{url=new URL(connectionString);}catch{throw new GovernanceValidationError('GOVERNANCE_DATABASE_URL is invalid.');}if(!['postgres:','postgresql:'].includes(url.protocol))throw new GovernanceValidationError('GOVERNANCE_DATABASE_URL must use PostgreSQL.');return new PostgresGovernanceStore(new Pool({connectionString,max:10,connectionTimeoutMillis:5000,idleTimeoutMillis:30000,application_name:'enterprise-mcp-kit-governance'}));}
  async load(){await this.ensure();const client=await this.pool.connect();try{return await load(client);}finally{client.release();}}
  async save(snapshot:GovernanceSnapshot){await this.transact(()=>({snapshot,result:undefined}));}
  async transact<T>(operation:(snapshot:GovernanceSnapshot)=>Promise<{snapshot:GovernanceSnapshot;result:T}>|{snapshot:GovernanceSnapshot;result:T}):Promise<T>{await this.ensure();const client=await this.pool.connect();try{await client.query('BEGIN');await client.query("SELECT pg_advisory_xact_lock(hashtext('enterprise-mcp-kit-governance'))");const current=await load(client,true),updated=await operation(current);validate(updated.snapshot);await client.query('INSERT INTO enterprise_mcp_governance_state(singleton,version,plans,receipts,updated_at) VALUES(TRUE,2,$1::jsonb,$2::jsonb,NOW()) ON CONFLICT(singleton) DO UPDATE SET version=2,plans=EXCLUDED.plans,receipts=EXCLUDED.receipts,updated_at=NOW()',[JSON.stringify(updated.snapshot.plans),JSON.stringify(updated.snapshot.receipts)]);for(const event of updated.snapshot.events)await client.query('INSERT INTO enterprise_mcp_governance_audit(id,plan_id,tenant_id,event,actor_id,occurred_at,reason) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO NOTHING',[event.id,event.planId,event.tenantId,event.event,event.actorId,event.occurredAt,event.reason]);await client.query('COMMIT');return updated.result;}catch(error){await client.query('ROLLBACK').catch(()=>{});if(error instanceof GovernanceValidationError)throw error;throw new GovernanceValidationError('PostgreSQL governance transaction failed.');}finally{client.release();}}
  async close(){await this.pool.end();}
  private async ensure(){if(!this.initialization)this.initialization=(async()=>{await this.pool.query('CREATE TABLE IF NOT EXISTS enterprise_mcp_governance_state(singleton boolean PRIMARY KEY DEFAULT TRUE CHECK(singleton),version integer NOT NULL CHECK(version=2),plans jsonb NOT NULL,receipts jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT NOW())');await this.pool.query('CREATE TABLE IF NOT EXISTS enterprise_mcp_governance_audit(id text PRIMARY KEY,plan_id text NOT NULL,tenant_id text NOT NULL,event text NOT NULL,actor_id text NOT NULL,occurred_at timestamptz NOT NULL,reason text NULL)');await this.pool.query('CREATE INDEX IF NOT EXISTS enterprise_mcp_governance_audit_plan_time ON enterprise_mcp_governance_audit(tenant_id,plan_id,occurred_at,id)');})();await this.initialization;}
}
async function load(client:PoolClient,lock=false):Promise<GovernanceSnapshot>{const state=await client.query(`SELECT version,plans,receipts FROM enterprise_mcp_governance_state WHERE singleton=TRUE${lock?' FOR UPDATE':''}`),audit=await client.query('SELECT id,plan_id,tenant_id,event,actor_id,occurred_at,reason FROM enterprise_mcp_governance_audit ORDER BY occurred_at,id');const snapshot=state.rowCount?{version:2 as const,plans:state.rows[0].plans,receipts:state.rows[0].receipts,events:audit.rows.map(row=>({id:row.id,planId:row.plan_id,tenantId:row.tenant_id,event:row.event,actorId:row.actor_id,occurredAt:new Date(row.occurred_at).toISOString(),reason:row.reason})as GovernanceAuditEvent)}:empty();validate(snapshot);return snapshot;}
function validate(snapshot:GovernanceSnapshot){if(snapshot?.version!==2||!Array.isArray(snapshot.plans)||!Array.isArray(snapshot.events)||!Array.isArray(snapshot.receipts))throw new GovernanceValidationError('Governance snapshot is invalid.');}
