export const siteInformationFields = ['physical_address', 'shipping_address', 'description', 'facility', 'time_zone'] as const;
export type SiteInformationField = typeof siteInformationFields[number];
export interface SiteInformationChange { field: SiteInformationField; expectedValue: string; newValue: string; expectedLastUpdated: string; }
export interface SiteInformationWriteRequest extends SiteInformationChange { siteId: number; tenantId: string; }
export interface SiteInformationWriteResult { siteId: number; siteName: string; tenantId: string; field: SiteInformationField; beforeValue: string; afterValue: string; beforeLastUpdated: string; afterLastUpdated: string; source: string; }
type Fetch = (input: URL | string, init?: RequestInit) => Promise<Response>;
export class NetBoxSiteWriteError extends Error { constructor(message: string) { super(message); this.name = 'NetBoxSiteWriteError'; } }
/** Fixed-endpoint writer for one allowlisted native site-information field. */
export class NetBoxSiteInformationWriter {
  private readonly baseUrl: URL; private readonly fetch: Fetch; private readonly timeoutMs: number;
  constructor(private readonly options: { baseUrl: string; token: string; timeoutMs?: number; fetch?: Fetch }) { if (!exact(options?.baseUrl) || !exact(options?.token)) throw new NetBoxSiteWriteError('NetBox site-write configuration is invalid.'); try { this.baseUrl = new URL(options.baseUrl.endsWith('/') ? options.baseUrl : `${options.baseUrl}/`); } catch { throw new NetBoxSiteWriteError('NetBox site-write base URL is invalid.'); } if (!['http:', 'https:'].includes(this.baseUrl.protocol) || this.baseUrl.username || this.baseUrl.password) throw new NetBoxSiteWriteError('NetBox site-write base URL is invalid.'); this.fetch = options.fetch ?? globalThis.fetch; this.timeoutMs = options.timeoutMs ?? 5_000; }
  async updateSiteInformation(input: SiteInformationWriteRequest): Promise<SiteInformationWriteResult> {
    validate(input); const path = `api/dcim/sites/${input.siteId}/`; const before = await this.request(path, 'GET'); const name = text(before.name); const tenant = nested(before, 'tenant', 'slug'); const version = text(before.last_updated); const current = text(before[input.field]) ?? '';
    if (!name || !version) throw new NetBoxSiteWriteError('NetBox returned incomplete site version evidence.'); if (tenant !== input.tenantId) throw new NetBoxSiteWriteError('NetBox site is outside the approved tenant scope.'); if (version !== input.expectedLastUpdated || current !== input.expectedValue) throw new NetBoxSiteWriteError('NetBox site changed after the plan was created.');
    const after = await this.request(path, 'PATCH', { [input.field]: input.newValue }); const afterValue = text(after[input.field]) ?? ''; const afterVersion = text(after.last_updated); if (afterValue !== input.newValue || !afterVersion) throw new NetBoxSiteWriteError('NetBox did not verify the approved site-information change.');
    return { siteId: input.siteId, siteName: name, tenantId: input.tenantId, field: input.field, beforeValue: current, afterValue, beforeLastUpdated: version, afterLastUpdated: afterVersion, source: text(after.url) ?? path };
  }
  private async request(path: string, method: 'GET' | 'PATCH', body?: unknown): Promise<Record<string, unknown>> { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), this.timeoutMs); try { const response = await this.fetch(new URL(path, this.baseUrl), { method, headers: { Authorization: `Bearer ${this.options.token}`, Accept: 'application/json', ...(body ? { 'Content-Type': 'application/json' } : {}) }, body: body ? JSON.stringify(body) : undefined, signal: controller.signal }); if (!response.ok) throw new NetBoxSiteWriteError(response.status === 403 ? 'NetBox site-write request was not authorized.' : response.status === 404 ? 'NetBox site was not found.' : 'NetBox site-write request failed.'); return await response.json() as Record<string, unknown>; } catch (error) { if (error instanceof NetBoxSiteWriteError) throw error; throw new NetBoxSiteWriteError((error as { name?: string }).name === 'AbortError' ? 'NetBox site-write request timed out.' : 'NetBox site-write request failed.'); } finally { clearTimeout(timer); } }
}
function validate(input: SiteInformationWriteRequest): void { const max = input?.field === 'description' ? 200 : input?.field === 'time_zone' ? 64 : 200; if (!input || !Number.isInteger(input.siteId) || input.siteId < 1 || !exact(input.tenantId) || !siteInformationFields.includes(input.field) || typeof input.expectedValue !== 'string' || typeof input.newValue !== 'string' || input.newValue.length > max || input.expectedValue.length > max || input.expectedValue === input.newValue || input.newValue.trim() !== input.newValue || /[\u0000-\u001f\u007f]/.test(input.newValue) || !exact(input.expectedLastUpdated) || Number.isNaN(Date.parse(input.expectedLastUpdated))) throw new NetBoxSiteWriteError('Approved site-information change is invalid.'); }
function text(value: unknown): string | null { return typeof value === 'string' ? value : null; } function exact(value: unknown): value is string { return typeof value === 'string' && value.length > 0 && value.trim() === value; } function nested(record: Record<string, unknown>, key: string, field: string): string | null { return text((record[key] as Record<string, unknown> | null)?.[field]); }
