import type{ProvisioningDiscovery}from'./site-provisioning-manifest.js';import type{ProvisionedRecord,SiteProvisioningAdapter}from'./site-provisioning-executor.js';
type Fetch=(input:URL|string,init?:RequestInit)=>Promise<Response>;export class NetBoxProvisioningError extends Error{constructor(message:string){super(message);this.name='NetBoxProvisioningError';}}
export class NetBoxSiteProvisioningAdapter implements SiteProvisioningAdapter,ProvisioningDiscovery{
  private readonly base:URL;private readonly fetch:Fetch;private readonly timeout:number;private tenantIds=new Map<string,number>();private refs=new Map<string,number>();
  constructor(private readonly options:{baseUrl:string;token:string;timeoutMs?:number;fetch?:Fetch}){if(!exact(options?.baseUrl)||!exact(options?.token))throw new NetBoxProvisioningError('NetBox provisioning configuration is invalid.');try{this.base=new URL(options.baseUrl.endsWith('/')?options.baseUrl:`${options.baseUrl}/`);}catch{throw new NetBoxProvisioningError('NetBox provisioning base URL is invalid.');}if(!['http:','https:'].includes(this.base.protocol)||this.base.username||this.base.password)throw new NetBoxProvisioningError('NetBox provisioning base URL is invalid.');this.fetch=options.fetch??globalThis.fetch;this.timeout=options.timeoutMs??5000;}
  async tenantExists(slug:string){const row=await this.unique(`api/tenancy/tenants/?slug=${encodeURIComponent(slug)}`);if(row)this.tenantIds.set(slug,id(row));return!!row;}
  async siteExists(name:string,slug:string){return!!(await this.unique(`api/dcim/sites/?slug=${encodeURIComponent(slug)}`))||!!(await this.unique(`api/dcim/sites/?name=${encodeURIComponent(name)}`));}
  async referencesExist(input:{deviceTypeSlugs:string[];roleSlugs:string[];platformSlugs:string[]}){return{missingDeviceTypes:await this.missing('api/dcim/device-types/','device-type',input.deviceTypeSlugs),missingRoles:await this.missing('api/dcim/device-roles/','role',input.roleSlugs),missingPlatforms:await this.missing('api/dcim/platforms/','platform',input.platformSlugs)}}
  async addressesInUse(addresses:string[]){const used:string[]=[];for(const address of addresses)if(await this.unique(`api/ipam/ip-addresses/?address=${encodeURIComponent(address)}`))used.push(address);return used;}
  async networkResourcesInUse(input:{vlanIds:number[];prefixes:string[]}){const vlanIds:number[]=[],prefixes:string[]=[];for(const vid of input.vlanIds)if(await this.any(`api/ipam/vlans/?vid=${vid}`))vlanIds.push(vid);for(const prefix of input.prefixes)if(await this.any(`api/ipam/prefixes/?prefix=${encodeURIComponent(prefix)}`))prefixes.push(prefix);return{vlanIds,prefixes};}
  async createSite(input:{tenantSlug:string;name:string;slug:string;facility:string;physicalAddress:string;timeZone:string}){const tenant=this.tenantIds.get(input.tenantSlug);if(!tenant)throw new NetBoxProvisioningError('Tenant reference was not resolved by discovery.');return id(await this.request('api/dcim/sites/','POST',{name:input.name,slug:input.slug,tenant,status:'planned',facility:input.facility,physical_address:input.physicalAddress,time_zone:input.timeZone}));}
  async createVlan(input:{siteId:number;tenantSlug:string;name:string;vid:number}){return id(await this.request('api/ipam/vlans/','POST',{site:input.siteId,tenant:this.tenant(input.tenantSlug),name:input.name,vid:input.vid,status:'active'}));}
  async createPrefix(input:{siteId:number;tenantSlug:string;prefix:string;vlanId:number|null;description:string}){return id(await this.request('api/ipam/prefixes/','POST',{scope_type:'dcim.site',scope_id:input.siteId,tenant:this.tenant(input.tenantSlug),prefix:input.prefix,vlan:input.vlanId,status:'active',description:input.description}));}
  async createRack(input:{siteId:number;tenantSlug:string;name:string;uHeight:number}){return id(await this.request('api/dcim/racks/','POST',{site:input.siteId,tenant:this.tenant(input.tenantSlug),name:input.name,status:'planned',u_height:input.uHeight,width:19}));}
  async createDevice(input:{siteId:number;tenantSlug:string;rackId:number;name:string;position:number;face:'front'|'rear';deviceTypeSlug:string;roleSlug:string;platformSlug:string|null}){return id(await this.request('api/dcim/devices/','POST',{name:input.name,tenant:this.tenant(input.tenantSlug),site:input.siteId,rack:input.rackId,position:input.position,face:input.face,status:'planned',device_type:this.ref('device-type',input.deviceTypeSlug),role:this.ref('role',input.roleSlug),platform:input.platformSlug?this.ref('platform',input.platformSlug):null}));}
  async createInterface(input:{deviceId:number;name:string}){return id(await this.request('api/dcim/interfaces/','POST',{device:input.deviceId,name:input.name,type:'1000base-t',enabled:true}));}
  async createIpAddress(input:{interfaceId:number;address:string;tenantSlug:string}){return id(await this.request('api/ipam/ip-addresses/','POST',{address:input.address,status:'active',tenant:this.tenant(input.tenantSlug),assigned_object_type:'dcim.interface',assigned_object_id:input.interfaceId}));}
  async deleteCreated(record:ProvisionedRecord){const roots:Record<ProvisionedRecord['kind'],string>={site:'api/dcim/sites/',vlan:'api/ipam/vlans/',prefix:'api/ipam/prefixes/',rack:'api/dcim/racks/',device:'api/dcim/devices/',interface:'api/dcim/interfaces/','ip-address':'api/ipam/ip-addresses/'};await this.request(`${roots[record.kind]}${record.id}/`,'DELETE');}
  private tenant(slug:string){const value=this.tenantIds.get(slug);if(!value)throw new NetBoxProvisioningError('Tenant reference was not resolved by discovery.');return value;}
  private async missing(path:string,kind:string,slugs:string[]){const missing:string[]=[];for(const slug of slugs){const row=await this.unique(`${path}?slug=${encodeURIComponent(slug)}`);if(!row)missing.push(slug);else this.refs.set(`${kind}:${slug}`,id(row));}return missing;}
  private ref(kind:string,slug:string){const value=this.refs.get(`${kind}:${slug}`);if(!value)throw new NetBoxProvisioningError('Provisioning reference was not resolved by discovery.');return value;}
  private async any(path:string){const result=await this.request(path,'GET')as{count?:number};return Number(result.count)>0;}
  private async unique(path:string){const result=await this.request(path,'GET')as{count?:number;results?:Record<string,unknown>[]};if(result.count===0)return null;if(result.count!==1||result.results?.length!==1)throw new NetBoxProvisioningError('NetBox discovery returned an ambiguous result.');return result.results[0];}
  private async request(path:string,method:'GET'|'POST'|'DELETE',body?:unknown):Promise<Record<string,unknown>>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),this.timeout);try{const response=await this.fetch(new URL(path,this.base),{method,headers:{Authorization:`Bearer ${this.options.token}`,Accept:'application/json',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal});if(!response.ok)throw new NetBoxProvisioningError(response.status===403?'NetBox provisioning request was not authorized.':response.status===404?'NetBox provisioning record was not found.':'NetBox provisioning request failed.');if(method==='DELETE')return{};try{return await response.json()as Record<string,unknown>;}catch{throw new NetBoxProvisioningError('NetBox provisioning returned invalid JSON.');}}catch(error){if(error instanceof NetBoxProvisioningError)throw error;throw new NetBoxProvisioningError((error as{name?:string}).name==='AbortError'?'NetBox provisioning request timed out.':'NetBox provisioning request failed.');}finally{clearTimeout(timer);}}
}
function id(row:Record<string,unknown>):number{if(!Number.isInteger(row.id)||Number(row.id)<1)throw new NetBoxProvisioningError('NetBox provisioning response omitted the record ID.');return Number(row.id);}function exact(value:unknown):value is string{return typeof value==='string'&&value.length>0&&value.trim()===value;}
