apiVersion: 1
prune: true
datasources:
  - name: Open Enterprise AIOps Prometheus
    uid: aiops-prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    editable: false
    version: 1
    jsonData:
      httpMethod: POST
      manageAlerts: false
      prometheusType: Prometheus
      prometheusVersion: 3.10.0
      timeInterval: 10s
